Сортировка массива строк
js-tasks-ru/js-20201211_valera545 pull request #3
Opened 2020-12-15 20:27 UTC by vharlamov

Очень трудно было догадаться, как прописать смешанную локаль. Нигде этого нет, догадался методом тыка, по наитию.

2020-12-15 21:30 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-12-15 22:26 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-12-15 23:15 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-12-17 23:05 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +        return tmpArr.sort( (a, b) => a.localeCompare( b, 'ru-en', { caseFirst:'upper', sensitivity:'case', usage:'sort' } ) );
строка 10 дублирует строку 12 за исключением порядка аргументов в методе `localeCompare` - попробуйте избавиться от дублирования.

проверьте использование `let` - возможно при объявлении переменной в данном решении нужен `const`?

2020-12-17 23:05 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    };
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2020-12-17 23:06 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    // for( let field of fields ) {
никогда, никогда не оставляйте закомментированный код - это очень плохая практика.
подробнее расскажу на занятии

2020-12-17 23:06 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    for( let [key, value] of Object.entries( obj ) ) {
good 👍

2020-12-17 23:06 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    let newList = {};
может `const`? как считаете?

2020-12-17 23:07 UTC, dosandk requested changes
необходимо исправить решение `sortStrings`. Проверить использование `let` и `const`

2020-12-18 07:57 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-12-18 09:20 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-12-18 09:44 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-12-18 10:18 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-12-20 13:21 UTC, dosandk approved these changes

2020-12-20 13:22 UTC, merged